project:
  type: website
  output-dir: docs

website:
  title: "Vadym Musiienko"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "My Projects"
        menu: 
         - text: "Wine Analysis"
           href: wine.html
         - text: "Acoustic Absorbance"
           href: WAI.html
         - text: "Sleep Science"
           href: sleep.html
         - text: "TidyTuesday Projects"
           href: mini.html
format:
  html:
    theme:
      light: minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full


