project:
  type: website
  output-dir: docs

website:
  title: "Vadym Musiienko"
  navbar:
    right:
      - text: "Data Science"
        menu: 
         - text: "Wine Reviews"
           href: wine.html
         - text: "Acoustic Absorbance"
           href: WAI.html
         - text: "Sleep Quality"
           href: sleep.html
         - text: "TidyTuesday Projects"
           href: mini.html
      - text: "Other"
        menu: 
          - text: "Motivational Coach"
            href: https://www.motivational-coach.com/
    tools:
      - icon: github
        href: https://github.com/vadymmusiienko/vadymmusiienko.github.io
format:
  html:
    theme:
      light: minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full


