project:
  type: website
  output-dir: docs

website:
  title: "Vadym Musiienko"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full


