project:
  type: website
  output-dir: docs

website:
  title: "Vadym Musiienko"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Data Viz"
        menu: 
         - text: "Wine reviews"
           href: wine.html
         - text: "International Mathematical Olympiad"
           href: imo.html
         - text: "Refugees"
           href: refugees.html
format:
  html:
    theme:
      light: minty
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full


