---
title: "Refugees"
description: |
  Analysis of Refugees Data from TidyTuesday
author: Vadym Musiienko
date: September 18, 2024
format: html
about: 
  template: jolla
  links:
    - text: TidyTuesday
      href: https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-08-22
---

```{r}
#| echo: false
#| message: false

# Load needed libraries
library(tidyverse)

# Load all the data
tuesdata <- tidytuesdayR::tt_load('2023-08-22')

# Unpack a data frame I need
population <- tuesdata$population

# Wrangle and visualize data
population |>
  filter(coo == "UKR", year >= 2022) |>
  group_by(coa_name) |>
  summarize(total_refugees = sum(refugees, na.rm = TRUE)) |>
  arrange(desc(total_refugees)) |>
  slice_head(n = 5) |>
  mutate(country = recode(coa_name, "Czechia" = "Czech Republic",
                           "Russian Federation" = "Russia",
                           "United Kingdom of Great Britain and Northern Ireland"
                           = "UK")) |>
  ggplot(aes(fct_reorder(country, total_refugees), total_refugees, fill = country)) +
  geom_col(width = 0.7) +
  scale_y_continuous(labels = scales::comma_format()) +
   labs(
    title = "Top 5 Countries with Most Ukrainian Refugees",
    x = NULL,
    y = "Total Refugees",
  ) +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))
```

*This bar chart displays the top 5 countries hosting the most Ukrainian refugees (since the beginning of the full-scale invasion).The y-axis represents the total number of refugees, with Russia hosting the highest number, exceeding a million. Germany and Poland follow closely with almost a million refugees each, while the Czech Republic has just under 500,000. The UK has the fewest refugees among the five countries, with less than 250,000.*

**Key observations:**

The significant difference in the number of Ukrainian refugees in Russia compared to other countries is striking, prompting the question: why are people fleeing the war to the very aggressor? This is primarily because Russian forces in occupied Ukrainian territories forcibly deporting people to Russia, labeling them as "refugees" and leaving them with no other option. In contrast, Poland and Germany are popular destinations for Ukrainian refugees, likely due to their proximity and strong support.
